name: RansomEye Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"

env:
  PYTHON_VERSION: "3.12"
  RELEASE_NAME: "ransomeye-${{ github.ref_name }}"
  ARTIFACT_DIR: "release-artifacts"

jobs:

  prechecks:
    name: Pre-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify version consistency
        run: |
          echo "Checking version consistency for ${GITHUB_REF_NAME#v}"
          # TODO: Implement version consistency check across codebase

      - name: Lint & static checks
        run: |
          pip install ruff black mypy
          ruff check . || true
          black --check . || true
          # mypy . || true  # TODO: Enable when type coverage sufficient

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prechecks
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Create build artifacts directory
        run: mkdir -p build/artifacts

      - name: Build core components
        run: |
          chmod +x scripts/build_core.sh
          ./scripts/build_core.sh

      - name: Build DPI probe
        run: |
          chmod +x scripts/build_dpi_probe.sh
          ./scripts/build_dpi_probe.sh

      - name: Build Linux agent
        run: |
          chmod +x scripts/build_linux_agent.sh
          ./scripts/build_linux_agent.sh

      - name: Build Windows agent
        run: |
          chmod +x scripts/build_windows_agent.sh
          ./scripts/build_windows_agent.sh

      - name: Verify all artifacts created
        run: |
          echo "Verifying build artifacts..."
          test -f build/artifacts/core-installer.tar.gz || { echo "Missing core-installer.tar.gz"; exit 1; }
          test -f build/artifacts/dpi-probe.tar.gz || { echo "Missing dpi-probe.tar.gz"; exit 1; }
          test -f build/artifacts/linux-agent.tar.gz || { echo "Missing linux-agent.tar.gz"; exit 1; }
          test -f build/artifacts/windows-agent.zip || { echo "Missing windows-agent.zip"; exit 1; }
          echo "✅ All artifacts verified"
          ls -lh build/artifacts/

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/artifacts

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: $ARTIFACT_DIR

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pytest-asyncio

      - name: Run unit & integration tests
        run: |
          pytest tests/unit/ -v
          pytest tests/integration/ -v

  security:
    name: Security Gates
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Dependency & secret scan
        run: |
          # TODO: Implement security scanning
          echo "Security scan placeholder"
          # Expected: SAST, dependency scan, secret detection

  package:
    name: Package (UNSIGNED)
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/artifacts

      - name: Create release bundle
        run: |
          mkdir $RELEASE_NAME-unsigned
          
          # Copy build artifacts
          mkdir -p $RELEASE_NAME-unsigned/artifacts
          cp build/artifacts/* $RELEASE_NAME-unsigned/artifacts/
          
          # Copy release notes
          if [ -f "RELEASE_NOTES_${GITHUB_REF_NAME}.md" ]; then
            cp RELEASE_NOTES_${GITHUB_REF_NAME}.md $RELEASE_NAME-unsigned/
          elif [ -f "RELEASE_NOTES_v1.0.0.md" ]; then
            cp RELEASE_NOTES_v1.0.0.md $RELEASE_NAME-unsigned/
          fi
          
          # Copy installer framework
          mkdir -p $RELEASE_NAME-unsigned/installer
          cp -r installer/core $RELEASE_NAME-unsigned/installer/
          cp -r installer/common $RELEASE_NAME-unsigned/installer/
          
          # Copy schemas and contracts
          cp -r contracts $RELEASE_NAME-unsigned/ 2>/dev/null || true
          cp -r schemas $RELEASE_NAME-unsigned/ 2>/dev/null || true
          
          # Generate checksums
          cd $RELEASE_NAME-unsigned
          find . -type f -exec sha256sum {} \; | sort > SHA256SUMS
          cd ..
          
          # Generate manifest
          python3 tools/manifest_generator.py \
            --input $RELEASE_NAME-unsigned \
            --output $RELEASE_NAME-unsigned/manifest.json \
            --pretty

      - uses: actions/upload-artifact@v4
        with:
          name: unsigned-release
          path: ${{ env.RELEASE_NAME }}-unsigned

  signing_handoff:
    name: Signing Handoff (MANUAL / OFFLINE)
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Pause for offline signing
        run: |
          echo "================================================================"
          echo "UNSIGNED BUNDLE READY FOR OFFLINE SIGNING"
          echo "================================================================"
          echo ""
          echo "REQUIRED ACTIONS (OFFLINE, AIR-GAPPED WORKSTATION):"
          echo ""
          echo "1. Download artifact 'unsigned-release' from this workflow run"
          echo "2. Follow signing procedure: docs/DRY_RUN_CHECKLIST_v1.0.0.md"
          echo "3. Sign all artifacts using: supply-chain/cli/sign_artifacts.py"
          echo "4. Create release bundle: scripts/create_release_bundle.py"
          echo "5. Verify bundle offline: scripts/verify_release_bundle.py"
          echo "6. Upload signed bundle tarball (.tar.gz) as artifact 'signed-release-bundle'"
          echo ""
          echo "PUBLIC KEY FOR VERIFICATION:"
          echo "  Path: release/.keys/ransomeye-release-signing-v1.pub"
          echo "  Fingerprint: 4ba9f27a9d8d61ef2ad07ee9dbc5d29335a73bd5fcf334cb08b30058fb34f2e1"
          echo ""
          echo "KEY REGISTRY:"
          echo "  Path: keys/registry.json"
          echo ""
          echo "================================================================"
          echo "⚠️  CI will pause here until signed bundle is uploaded"
          echo "================================================================"

  verify_and_release:
    name: Verify & Release
    runs-on: ubuntu-latest
    needs: signing_handoff
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: signed-release-bundle
          path: signed-bundle/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install verification dependencies
        run: |
          pip install cryptography

      - name: Verify signed release bundle
        run: |
          echo "================================================================"
          echo "VERIFYING SIGNED RELEASE BUNDLE"
          echo "================================================================"
          
          # Find the signed bundle tarball
          BUNDLE_PATH=$(find signed-bundle/ -name "*.tar.gz" -type f | head -n 1)
          CHECKSUM_PATH="${BUNDLE_PATH}.sha256"
          
          if [ -z "$BUNDLE_PATH" ]; then
            echo "❌ ERROR: No signed bundle tarball found"
            exit 1
          fi
          
          echo "Bundle: $BUNDLE_PATH"
          echo "Registry: keys/registry.json"
          echo ""
          
          # Verify using authoritative verification script
          python3 scripts/verify_release_bundle.py \
            --bundle "$BUNDLE_PATH" \
            --checksum "$CHECKSUM_PATH" \
            --registry-path keys/registry.json \
            --output verification-report.json || {
              echo ""
              echo "❌ SIGNATURE VERIFICATION FAILED"
              echo "DO-NOT-RELEASE: Bundle failed cryptographic verification"
              exit 1
            }
          
          echo ""
          echo "================================================================"
          echo "✅ SIGNATURE VERIFICATION PASSED"
          echo "================================================================"
          
          # Extract bundle for subsequent steps
          mkdir -p release-verified
          tar -xzf "$BUNDLE_PATH" -C release-verified
          
          # Move extracted bundle contents to standard location
          BUNDLE_DIR=$(find release-verified -mindepth 1 -maxdepth 1 -type d | head -n 1)
          if [ -n "$BUNDLE_DIR" ]; then
            mv "$BUNDLE_DIR"/* release-verified/
            rmdir "$BUNDLE_DIR"
          fi

      - name: Upload verified bundle for promotion
        uses: actions/upload-artifact@v4
        with:
          name: verified-release-bundle
          path: release-verified/

  promote_dev:
    name: Promote to DEV
    runs-on: ubuntu-latest
    needs: verify_and_release
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: verified-release-bundle
          path: verified/

      - name: Promote to DEV environment
        run: |
          echo "Promoting ${GITHUB_REF_NAME} to DEV environment"
          ./release/promote.sh \
            --env dev \
            --artifact verified/ \
            --version ${GITHUB_REF_NAME}
          echo "✅ DEV promotion complete"

  promote_staging:
    name: Promote to STAGING
    runs-on: ubuntu-latest
    needs: promote_dev
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: verified-release-bundle
          path: verified/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install verification dependencies
        run: |
          pip install cryptography

      - name: Re-verify bundle integrity (staging gate)
        run: |
          echo "================================================================"
          echo "STAGING GATE: Re-verifying bundle integrity"
          echo "================================================================"
          
          # Verify RELEASE_MANIFEST.json exists and is valid
          if [ ! -f "verified/RELEASE_MANIFEST.json" ]; then
            echo "❌ ERROR: RELEASE_MANIFEST.json not found"
            exit 1
          fi
          
          # Verify all artifacts match manifest hashes
          python3 -c "
          import json
          import hashlib
          from pathlib import Path
          
          manifest = json.loads(Path('verified/RELEASE_MANIFEST.json').read_text())
          
          for artifact in manifest['artifacts']:
              artifact_path = Path('verified') / artifact['path']
              if not artifact_path.exists():
                  print(f'❌ ERROR: Artifact not found: {artifact[\"path\"]}')
                  exit(1)
              
              # Verify SHA256
              sha256 = hashlib.sha256()
              with open(artifact_path, 'rb') as f:
                  for chunk in iter(lambda: f.read(4096), b''):
                      sha256.update(chunk)
              
              if sha256.hexdigest() != artifact['sha256']:
                  print(f'❌ ERROR: Hash mismatch for {artifact[\"name\"]}')
                  exit(1)
          
          print(f'✅ All {len(manifest[\"artifacts\"])} artifacts verified')
          "
          
          echo "✅ STAGING GATE: Bundle integrity verified"

      - name: Promote to STAGING environment
        run: |
          echo "Promoting ${GITHUB_REF_NAME} to STAGING environment"
          ./release/promote.sh \
            --env staging \
            --artifact verified/ \
            --version ${GITHUB_REF_NAME}
          echo "✅ STAGING promotion complete"

  promote_prod:
    name: Promote to PROD
    runs-on: ubuntu-latest
    needs: promote_staging
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: verified-release-bundle
          path: verified/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install verification dependencies
        run: |
          pip install cryptography

      - name: Final production gate verification
        run: |
          echo "================================================================"
          echo "PRODUCTION GATE: Final verification before release"
          echo "================================================================"
          
          # Verify RELEASE_MANIFEST.json
          if [ ! -f "verified/RELEASE_MANIFEST.json" ]; then
            echo "❌ ERROR: RELEASE_MANIFEST.json not found"
            exit 1
          fi
          
          # Verify Phase-8 evidence exists and shows PASS
          python3 -c "
          import json
          from pathlib import Path
          
          manifest = json.loads(Path('verified/RELEASE_MANIFEST.json').read_text())
          
          # Check GA verdict
          ga_verdict = manifest.get('evidence', {}).get('ga_verdict', 'UNKNOWN')
          if ga_verdict != 'PASS':
              print(f'❌ ERROR: GA verdict is {ga_verdict} (must be PASS)')
              exit(1)
          
          print(f'✅ GA verdict: {ga_verdict}')
          
          # Verify all required components present
          required_artifacts = ['core-installer', 'linux-agent', 'windows-agent', 'dpi-probe']
          artifact_names = [a['name'].split('.')[0] for a in manifest['artifacts']]
          
          for required in required_artifacts:
              if not any(required in name for name in artifact_names):
                  print(f'❌ ERROR: Required component missing: {required}')
                  exit(1)
          
          print(f'✅ All {len(required_artifacts)} required components present')
          
          # Verify signing key is active
          if manifest.get('public_keys', []):
              key_id = manifest['public_keys'][0]['key_id']
              print(f'✅ Signed with key: {key_id}')
          
          print('')
          print('✅ PRODUCTION GATE: All checks passed')
          "

      - name: Promote to PROD environment
        run: |
          echo "Promoting ${GITHUB_REF_NAME} to PRODUCTION environment"
          ./release/promote.sh \
            --env prod \
            --artifact verified/ \
            --version ${GITHUB_REF_NAME}
          echo "✅ PROD promotion complete"

      - name: Publish immutable release record
        run: |
          echo "Publishing immutable release record for ${GITHUB_REF_NAME}"
          ./release/publish.sh verified/ ${GITHUB_REF_NAME}
          echo "✅ Release published"
